server:
  port: 5920
  servlet:
    context-path: /api/chat


spring:
  servlet:
    multipart:
      max-file-size: 150MB
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/charles
    username: postgres
  jpa:
    generate-ddl: true
    open-in-view: true
    properties:
      hibernate:
        #format_sql: true
        show-sql: true
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create-drop
        jdbc:
          time_zone: GMT+8
  enable:
    scheduling: true